### ISSUE TITLE
Separate Repo

### ISSUE THREAD

**Issue by circleous** [cetfor/CyberspaceCamp#1]
Can you make it on a separate repo for every youtube series you've made or make it as project specific? Like anti-dbg on anti-dbg repo, HSL-Trainer on HSL-trainer, .. and so on. This make community help to improve the code easier. Thanks.

**Comment by cetfor** [comment]
Sure thing! I'll part these into their own repos tonight. Thanks :) 👍

**Comment by cetfor** [comment]
Ok, I've split these up. 
https://github.com/cetfor/HackSlashLootTrainer
https://github.com/cetfor/AntiDBG

Code will be maintained in their own repos from now on. Thanks again. :)
